### ISSUE TITLE
Perhaps we could export dob as date_of_birth

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/ageutil#2]
From README.md I read:

```python
from ageutil import dob
```

My first thought was what does "dob" mean. Perhaps use a longer name such as date_of_birth:

I somebody like to use it a lot and would like to avoid typing it can be imported using

```python
from ageutil import date_of_birth as dob
```

This makes the function more clear to the readers.

**Comment by bbonf** [comment]
Thanks, changed in b55f2df020acee8d5de03e6934a824a5c05d521c
